# Generated by Django 4.2.1 on 2023-05-18 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
